version: "3"

services:
  db:
    image: mysql
    container_name: MYSQL-DOCKER
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "tp1_db"
    volumes:
      - ./schemas:/var/lib/mysql