version: "3"

services:
  db:
    image: mysql
    container_name: MYSQL-DOCKER
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "integrador1"
    volumes:
      - ./schemas:/var/lib/mysql