server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: msvc-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/usuarios_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: monopatines
          uri: http://localhost:8090
          predicates:
            - Path=/api/monopatin/**
        - id: mantenimientos
          uri: http://localhost:8091
          predicates:
            - Path=/api/mantenimiento/**
        - id: paradas
          uri: http://localhost:8092
          predicates:
            - Path=/api/parada/**
        - id: tarifas
          uri: http://localhost:8093
          predicates:
            - Path=/api/tarifa/**
        - id: viajes
          uri: http://localhost:8094
          predicates:
            - Path=/api/viaje/**
        - id: pagos
          uri: http://localhost:8095
          predicates:
            - Path=/api/pago/**
