server:
  port: 8092

spring:
  application:
    name: msvc-parada
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/
      database: paradas_db
  jackson:
    deserialization:
      fail-on-unknown-properties: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka