server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: monopatines
          uri: http://localhost:8090
          predicates:
            - Path=/api/monopatin/**
        - id: mantenimientos
          uri: http://localhost:8091
          predicates:
            - Path=/api/mantenimiento/**
