version: "3"

services:
  db:
    image: mysql
    container_name: MYSQL-DOCKER
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "integrador2"
    volumes:
      - ./schemas:/var/lib/mysql